CREATE TABLE IF NOT EXISTS projects(
    id  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name    text NOT NULL CHECK (name <> ''),
    priority    integer NOT NULL,
    description text,
    deliverydate    date NOT NULL
);
CREATE TABLE IF NOT EXISTS tasks(
    id  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done    BOOLEAN,
    projectID   INTEGER REFERENCES projects(id)
);

-- INSERT PROJECTS DATA.
INSERT INTO projects(name, priority, description, deliverydate) VALUES 
    ('Make a web app', 1, 'Using JavaScript', '2022-04-09'),
    ('Make an app', 1, 'Using Dart', '2022-04-10'),
    ('Make a desktop app', 2, 'Using C++', '2023-04-09');

-- INSERT TASKS DATA.
INSERT INTO tasks(name, done, projectID) VALUES
    ('Download VueJs', false, 1),
    ('Create UI Web', false, 1),
    ('Download Flutter', false, 2),
    ('Design UI', false, 2);
